import eosio cdt 1.8 files

diff --git a/scripts/generate_package.sh.in b/scripts/generate_package.sh.in
--- a/scripts/generate_package.sh.in
+++ b/scripts/generate_package.sh.in
@@ -1,12 +1,21 @@
 #! /bin/bash
 
 VARIANT=$1
+if [[ ${VARIANT} == "deb" ]]; then
+    if [ -z "$2" ]; then
+        echo "Error, OS argument missing for deb package type"
+        exit -1
+    else
+        OS=$2
+    fi
+fi
 
 VERSION_NO_SUFFIX="@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@"
 VERSION_SUFFIX="@VERSION_SUFFIX@"
 VERSION="@VERSION_FULL@"
 
-BUILD_DIR="@CMAKE_BINARY_DIR@"
+# Using CMAKE_BINARY_DIR uses an absolute path and will break cross-vm building/download/make functionality
+BUILD_DIR="../../build"
 
 VENDOR="@VENDOR@"
 PROJECT="@PROJECT_NAME@"
@@ -24,21 +33,17 @@ export DESC
 export URL
 export EMAIL
 
-mkdir tmp
+mkdir -p tmp
 
 if [[ ${VARIANT} == "brew" ]]; then
-   bash generate_bottle.sh
+   . ./generate_bottle.sh
 elif [[ ${VARIANT} == "deb" ]]; then
-   bash generate_deb.sh
+   . ./generate_deb.sh ${OS}
 elif [[ ${VARIANT} == "rpm" ]]; then
-   bash generate_rpm.sh
+   . ./generate_rpm.sh
 else
    echo "Error, unknown package type. Use either ['brew', 'deb', 'rpm']."
    exit -1
 fi
 
-BUILDSTATUS=$?
-
-rm -r tmp
-
-exit $BUILDSTATUS
+rm -r tmp || exit 1
